development:
 
  google_client_id:             <%= ENV["GOOGLE_CLIENT_ID"] %>                              
  google_client_secret:         <%= ENV["GOOGLE_CLIENT_SECRET"] %>


test:
 
  google_client_id:             <%= ENV["GOOGLE_CLIENT_ID"] %>                              
  google_client_secret:         <%= ENV["GOOGLE_CLIENT_SECRET"] %>

production:
 
  google_client_id:             <%= ENV["GOOGLE_CLIENT_ID"] %>                              
  google_client_secret:         <%= ENV["GOOGLE_CLIENT_SECRET"] %>


